use std::{fs, path::PathBuf, process::Command, sync::{Once,atomic::{AtomicU64,Ordering}}};
use titus_lab_integration_stage_1_kernel::{complete_validation_handoff, synthetic_request, DeterministicLocalExecutor, IntegrationKernel, KernelResult};
use titus_lab_integration_stage_2_engagement_domain::*;

static NEXT:AtomicU64=AtomicU64::new(0);static BUILD:Once=Once::new();
fn repo()->PathBuf{PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()}
fn validator()->PathBuf{BUILD.call_once(||{assert!(Command::new("cargo").args(["build","--quiet","--manifest-path","INTEGRATION_STAGE_1_KERNEL/Cargo.toml","--bin","stage1_independent_validator"]).current_dir(repo()).status().unwrap().success())});repo().join("INTEGRATION_STAGE_1_KERNEL/target/debug/stage1_independent_validator")}
fn authority(client:&str,engagement:Option<&str>)->AuthorityGrant{AuthorityGrant{context_id:"synthetic-client-A".into(),client_id:client.into(),engagement_id:engagement.map(str::to_owned),operations:all_operations(),generation:1,current:true}}
fn base()->(EngagementDomain,String,String,AuthorityGrant){let mut d=EngagementDomain::default();let cid=client_identity("synthetic-client-A","Synthetic Industrial Client","synthetic:client-source");let cg=authority(&cid,None);d.create_client("synthetic-client-A","Synthetic Industrial Client","ORGANIZATION","synthetic:client-source",&cg).unwrap();let eid=d.create_engagement(&cid,"Operational Improvement Assessment",EngagementType::Operations,WorkingLanguage::Es,"synthetic-human-principal","synthetic:engagement-source",&cg).unwrap();let eg=authority(&cid,Some(&eid));(d,cid,eid,eg)}
fn stage1_pass()->(PathBuf,KernelResult){let root=std::env::temp_dir().join(format!("titus-stage2-stage1-{}-{}",std::process::id(),NEXT.fetch_add(1,Ordering::SeqCst)));let k=IntegrationKernel::create(&root,"synthetic-client-A",1,DeterministicLocalExecutor).unwrap();let mut r=k.execute(&synthetic_request());complete_validation_handoff(&repo(),&validator(),&mut r).unwrap();(root,r)}
fn complete_domain()->(EngagementDomain,String,AuthorityGrant,PathBuf){let(d0,_cid,eid,g)=base();let mut d=d0;d.define_objective(&eid,1,"Improve bounded operations","Evaluate evidence and recommend action","synthetic:objective",&g).unwrap();d.change_working_language(&eid,2,WorkingLanguage::Es,"synthetic:language",&g).unwrap();let s=d.register_source(&eid,3,"EN","synthetic://english-source","sha256:synthetic-source","synthetic:source",&g).unwrap();d.register_evidence(&eid,4,&s,ClaimClass::Fact,"synthetic:evidence",&g).unwrap();d.add_requirement(&eid,5,"Measure cycle time",&s,"synthetic:requirement",&g).unwrap();d.create_workstream(&eid,6,"operations","synthetic:workstream",&g).unwrap();d.request_decision(&eid,7,DecisionType::Pilot,"recommendation:bounded-pilot","synthetic:decision",&g).unwrap();d.register_deliverable(&eid,8,"Operational Assessment",vec![s],false,"synthetic:deliverable",&g).unwrap();d.register_build(&eid,9,"synthetic://future-build","synthetic:build",&g).unwrap();d.transition(&eid,10,Lifecycle::Active,"synthetic:activate",&g).unwrap();let(root,r)=stage1_pass();d.attach_stage1_gate(&eid,11,&r,"synthetic:stage1-gate",&g).unwrap();(d,eid,g,root)}

#[test]fn complete_synthetic_engagement_reaches_human_eligible_state(){let(d,eid,_,root)=complete_domain();let e=d.engagement(&eid).unwrap();assert_eq!(e.lifecycle(),Lifecycle::AwaitingHumanDecision);assert_eq!(e.working_language(),WorkingLanguage::Es);assert_eq!(e.sources()[0].original_language,"EN");assert_eq!(e.version(),12);assert_eq!(e.stage1_gate().unwrap().validator_verdict,"CERTIFIED_PASS");assert_eq!(e.requirements().len(),1);assert_eq!(e.workstreams().len(),1);assert_eq!(e.decisions().len(),1);assert_eq!(e.deliverables().len(),1);assert_eq!(e.builds().len(),1);fs::remove_dir_all(root).unwrap()}
#[test]fn wrong_context_is_rejected(){let(mut d,cid,_,_)=base();let mut g=authority(&cid,None);g.context_id="foreign".into();assert_eq!(d.create_client("synthetic-client-A","Synthetic Industrial Client","ORG","p",&g),Err(DomainError::InvalidContext))}
#[test]fn missing_authority_is_rejected(){let(mut d,_cid,eid,mut g)=base();g.operations.clear();assert_eq!(d.define_objective(&eid,1,"p","o","x",&g),Err(DomainError::MissingAuthority))}
#[test]fn cross_engagement_mutation_is_blocked(){let(mut d,cid,eid,ga)=base();let other=d.create_engagement(&cid,"Other",EngagementType::Research,WorkingLanguage::En,"actor","other",&authority(&cid,None)).unwrap();let gb=authority(&cid,Some(&other));assert_eq!(d.define_objective(&eid,1,"p","o","x",&gb),Err(DomainError::CrossEngagementMutation));let source=d.register_source(&eid,1,"EN","synthetic://owned-a","hash-a","source-a",&ga).unwrap();let evidence=d.register_evidence(&eid,2,&source,ClaimClass::Fact,"evidence-a",&ga).unwrap();d.add_requirement(&eid,3,"requirement-a",&source,"requirement-a",&ga).unwrap();d.create_workstream(&eid,4,"operations","workstream-a",&ga).unwrap();d.request_decision(&eid,5,DecisionType::Pilot,"recommendation-a","decision-a",&ga).unwrap();let build=d.register_build(&eid,6,"synthetic://build-a","build-a",&ga).unwrap();d.register_deliverable(&eid,7,"deliverable-a",vec![source.clone(),evidence.clone(),build],false,"deliverable-a",&ga).unwrap();d.define_objective(&eid,8,"problem-a","objective-a","objective-a",&ga).unwrap();let a=d.engagement(&eid).unwrap();assert_eq!(a.objective().unwrap().engagement_id(),eid);assert_eq!(a.sources()[0].engagement_id(),eid);assert_eq!(a.evidence()[0].engagement_id(),eid);assert_eq!(a.requirements()[0].engagement_id(),eid);assert_eq!(a.workstreams()[0].engagement_id(),eid);assert_eq!(a.decisions()[0].engagement_id(),eid);assert_eq!(a.builds()[0].engagement_id(),eid);assert_eq!(a.deliverables()[0].engagement_id(),eid);assert_eq!(d.register_evidence(&other,1,&source,ClaimClass::Fact,"foreign",&gb),Err(DomainError::EvidenceInvariant));assert_eq!(d.add_requirement(&other,1,"foreign",&source,"foreign",&gb),Err(DomainError::EvidenceInvariant));assert_eq!(d.register_deliverable(&other,1,"foreign",vec![source],false,"foreign",&gb),Err(DomainError::EvidenceInvariant))}
#[test]fn stale_write_is_rejected(){let(mut d,_,eid,g)=base();d.define_objective(&eid,1,"p","o","x",&g).unwrap();assert_eq!(d.change_working_language(&eid,1,WorkingLanguage::En,"late",&g),Err(DomainError::StaleWrite))}
#[test]fn invalid_transition_is_rejected(){let(mut d,_,eid,g)=base();assert_eq!(d.transition(&eid,1,Lifecycle::Closed,"invalid",&g),Err(DomainError::InvalidTransition))}
#[test]fn language_change_preserves_source_and_provenance(){let(mut d,_,eid,g)=base();d.define_objective(&eid,1,"p","o","x",&g).unwrap();let s=d.register_source(&eid,2,"EN","synthetic://source","hash","source-prov",&g).unwrap();let before=d.engagement(&eid).unwrap().sources()[0].clone();d.change_working_language(&eid,3,WorkingLanguage::En,"language-prov",&g).unwrap();assert_eq!(&before,&d.engagement(&eid).unwrap().sources()[0]);let localized=d.localized_artifact(&eid,&s,WorkingLanguage::Es,"derived-prov").unwrap();assert_eq!(localized.original_language,"EN");assert_eq!(localized.source_id,s)}
#[test]fn deliverable_cannot_be_original_evidence(){let(mut d,_,eid,g)=base();assert_eq!(d.register_deliverable(&eid,1,"Report",vec![],true,"p",&g),Err(DomainError::EvidenceInvariant))}
#[test]fn human_principal_bypass_is_blocked(){let(mut d,_,eid,g)=base();d.define_objective(&eid,1,"p","o","x",&g).unwrap();d.transition(&eid,2,Lifecycle::Active,"active",&g).unwrap();let root=std::env::temp_dir().join(format!("titus-stage2-bypass-{}",NEXT.fetch_add(1,Ordering::SeqCst)));let k=IntegrationKernel::create(&root,"synthetic-client-A",1,DeterministicLocalExecutor).unwrap();let unvalidated=k.execute(&synthetic_request());assert_eq!(d.attach_stage1_gate(&eid,3,&unvalidated,"gate",&g),Err(DomainError::HumanPrincipalBypass));fs::remove_dir_all(root).unwrap()}
#[test]fn closed_engagement_mutation_is_rejected(){let(mut d,eid,g,root)=complete_domain();let result_id=d.engagement(&eid).unwrap().stage1_gate().unwrap().result_id.clone();assert_eq!(d.apply_human_decision(&eid,12,"not-human-principal",&result_id,true,"invalid-human",&g),Err(DomainError::HumanPrincipalBypass));d.apply_human_decision(&eid,12,"human-principal:titus-lab",&result_id,true,"human-close",&g).unwrap();assert_eq!(d.change_working_language(&eid,13,WorkingLanguage::En,"late",&g),Err(DomainError::ClosedEngagement));fs::remove_dir_all(root).unwrap()}
#[test]fn deterministic_reexecution_matches(){let(a,eida,_,ra)=complete_domain();let(b,eidb,_,rb)=complete_domain();assert_eq!(eida,eidb);assert_eq!(a.engagement(&eida),b.engagement(&eidb));fs::remove_dir_all(ra).unwrap();fs::remove_dir_all(rb).unwrap()}
#[test]fn requirement_without_engagement_is_rejected(){let(mut d,cid,_,_)=base();assert_eq!(d.add_requirement("missing",1,"r","s","p",&authority(&cid,Some("missing"))),Err(DomainError::InvalidEngagement))}
